language: generic

matrix:
  include:
    - env: EMACS=emacs23
      sudo: false
      addons:
        apt:
          packages: ['emacs23-gtk', 'emacs23-el']
    - env: EMACS=emacs24
      sudo: false
      addons:
        apt:
          packages: ['emacs24-gtk', 'emacs24-el']
    - env: EMACS=emacs-snapshot
      sudo: true

install:
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
       sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
       sudo apt-get -qq update &&
       sudo apt-get -qq -f install &&
       sudo apt-get -qq install emacs-snapshot &&
       sudo apt-get -qq install emacs-snapshot-el;
    fi

# Emacs 23 does not come with ERT.  Download it and have emacs find it
before_script:
  - if [ "$EMACS" = 'emacs23' ]; then
       curl -Os https://raw.githubusercontent.com/ohler/ert/c619b56c5bc6a866e33787489545b87d79973205/lisp/emacs-lisp/ert.el &&
       export EMACSLOADPATH=$(emacs -batch -eval "(princ (mapconcat 'identity load-path \":\"))") &&
       export EMACSLOADPATH="$EMACSLOADPATH:$PWD";
    fi

script:
  - ./run_rust_emacs_tests.sh

notifications:
  email: false
